#!/usr/bin/env python3
"""Labops voice pass batch 5 — settings, editableTodoCard, mindMap, chatAssistant, mobileChatInterface,
warRoom, swarmDesk, spells, admin, and remaining misc sections."""
import json

THEMES_DIR = "/Users/d.edens/lab/madness_interactive/projects/common/Inventorium/src/locales/themes"

def load(name):
    with open(f"{THEMES_DIR}/{name}.json") as f:
        return json.load(f)

def save(name, data):
    with open(f"{THEMES_DIR}/{name}.json", "w") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
        f.write("\n")

def set_key(data, path, value):
    keys = path.split(".")
    cur = data
    for k in keys[:-1]:
        if k not in cur or not isinstance(cur[k], dict):
            cur[k] = {}
        cur = cur[k]
    if isinstance(cur, dict):
        cur[keys[-1]] = value

labops = load("labops")

patches = {
    # settings.export/import
    "settings.export.starting": "Initiating export...",
    "settings.export.error": "Export failed: {{error}}",
    "settings.import.starting": "Initiating import...",
    "settings.import.success": "Import complete! Imported {{importedCount}} items. {{skippedCount}} items skipped.",
    "settings.import.error": "Import failed: {{error}}",
    "settings.import.fileDialogError": "Failed to open file dialog",

    # settings.tabs
    "settings.tabs.profile": "Operator Profile",
    "settings.tabs.aiConfiguration": "AI Configuration",
    "settings.tabs.mcpSetup": "MCP Setup",
    "settings.tabs.messaging": "Messaging",
    "settings.tabs.apiKeys": "API Keys",
    "settings.tabs.mindMap": "Topology Map",
    "settings.tabs.umlData": "Code Visualizations",
    "settings.tabs.privacy": "Privacy",
    "settings.tabs.advanced": "Advanced",
    "settings.tabs.npcAgents": "NPC Agents",
    "settings.tabs.swarmDesk": "SwarmDesk",
    "settings.tabs.keyboardShortcuts": "Hotkeys",
    "settings.tabs.general": "General",
    "settings.tabs.notifications": "Alerts",
    "settings.tabs.security": "Security",

    # settings.swarmdesk
    "settings.swarmdesk.movementTitle": "Movement Speed Controls",
    "settings.swarmdesk.movementDescription": "Adjust camera movement speeds for Orbital and FPS modes in SwarmDesk 3D environment.",
    "settings.swarmdesk.resetDefaults": "Reset to Defaults",
    "settings.swarmdesk.orbitalTitle": "Orbital Mode (O key)",
    "settings.swarmdesk.orbitalDescription": "Controls camera movement when using orbital (free-fly) navigation.",
    "settings.swarmdesk.orbitalBaseSpeed": "Base Speed",
    "settings.swarmdesk.orbitalSprintMultiplier": "Sprint Multiplier (Ctrl held)",
    "settings.swarmdesk.fpsTitle": "FPS Mode (F key)",
    "settings.swarmdesk.fpsDescription": "Controls camera movement when using first-person navigation.",
    "settings.swarmdesk.fpsBaseSpeed": "Walk Speed",
    "settings.swarmdesk.fpsSprintSpeed": "Sprint Speed (Ctrl held)",

    # settings.messaging
    "settings.messaging.title": "Message Role Configuration",
    "settings.messaging.subtitle": "Configure which roles are allowed in chat messages. Core roles can be hidden but not deleted (they remain valid for backend validation).",
    "settings.messaging.allowedRoles": "Allowed Roles",
    "settings.messaging.addRole": "Add Role",
    "settings.messaging.editRole": "Edit Message Role",
    "settings.messaging.infoMessage": "These roles will be available when creating chat messages. Each role can have a custom emoji for visual identification. Core roles can be hidden but not deleted (they remain valid for backend validation).",
    "settings.messaging.roleId": "Role ID",
    "settings.messaging.roleIdHelper": "Lowercase, alphanumeric, and hyphens only (e.g., 'gpt-4', 'custom-ai')",
    "settings.messaging.roleIdDisabled": "Role ID cannot be changed",
    "settings.messaging.displayLabel": "Display Label",
    "settings.messaging.displayLabelHelper": "Human-readable name shown in console",
    "settings.messaging.emoji": "Emoji",
    "settings.messaging.emojiHelper": "Single emoji character for visual identification",
    "settings.messaging.coreRole": "Core Role",
    "settings.messaging.hidden": "Hidden",
    "settings.messaging.showRole": "Show role",
    "settings.messaging.hideRole": "Hide role",
    "settings.messaging.saveChanges": "Commit Changes",
    "settings.messaging.cancel": "Discard",
    "settings.messaging.npcConfig": "SwarmDesk NPC Configuration",
    "settings.messaging.npcEnabled": "Spawn as SwarmDesk NPC",
    "settings.messaging.npcCount": "NPC Count",
    "settings.messaging.npcCountHelper": "Choose how many clones of this role should appear in SwarmDesk (0-5).",
    "settings.messaging.npcColor": "NPC Color",
    "settings.messaging.npcColorHelper": "Used for the NPC body glow and sidebar identity color.",
    "settings.messaging.npcRole": "NPC Role Title",
    "settings.messaging.npcRoleHelper": "Shown above the NPC in SwarmDesk. Leave blank to use the display label.",
    "settings.messaging.npcPersonality": "NPC Personality",
    "settings.messaging.npcPersonalityHelper": "Controls the default vibe and fallback dialogue for this NPC.",
    "settings.messaging.npcPersonalities.helpful_assistant": "Helpful Assistant",
    "settings.messaging.npcPersonalities.chaotic_genius": "Chaotic Genius",
    "settings.messaging.npcPersonalities.methodical_precise": "Methodical & Precise",
    "settings.messaging.npcPersonalities.curious_explorer": "Curious Explorer",
    "settings.messaging.npcPersonalities.zen_creative": "Zen Creative",
    "settings.messaging.npcPersonalities.welcoming_efficient": "Welcoming & Efficient",
    "settings.messaging.npcPersonalities.organized_visionary": "Organized Visionary",
    "settings.messaging.duplicateRoleId": "A role with this ID already exists.",
    "settings.messaging.duplicateAgentId": "An agent with this ID already exists.",

    # editableTodoCard
    "editableTodoCard.confirmCancel": "You have uncommitted changes. Are you sure you want to discard?",
    "editableTodoCard.sections.metadata": "Metadata (Optional)",
    "editableTodoCard.errors.descriptionRequired": "Summary is required for diagnostic enhancement",
    "editableTodoCard.errors.aiEnhancementFailed": "Diagnostic enhancement failed: {{error}}",
    "editableTodoCard.errors.saveFailed": "Failed to commit changes",
    "editableTodoCard.placeholders.description": "Enter ticket summary...",
    "editableTodoCard.placeholders.clickToAdd": "Click to add summary...",
    "editableTodoCard.placeholders.enhancedDescription": "AI-enhanced summary will appear here...",
    "editableTodoCard.placeholders.notes": "Additional comments...",
    "editableTodoCard.placeholders.ticket": "Ticket reference...",
    "editableTodoCard.labels.enhancedDescription": "Enhanced Summary",
    "editableTodoCard.labels.aiEnhanced": "🧠 AI Enhanced Summary:",
    "editableTodoCard.labels.completionNotes": "✅ Resolution Notes:",
    "editableTodoCard.labels.completed": "Resolved",
    "editableTodoCard.labels.duration": "Duration",
    "editableTodoCard.labels.autoEnhanceOnSave": "Auto-enhance on commit",
    "editableTodoCard.labels.enhance": "Run Diagnostics",
    "editableTodoCard.labels.enhancing": "Running diagnostics...",
    "editableTodoCard.priority.low": "Low",
    "editableTodoCard.priority.medium": "Medium",
    "editableTodoCard.priority.high": "High",
    "editableTodoCard.priority.critical": "Critical",
    "editableTodoCard.status.pending": "Pending",
    "editableTodoCard.status.in_progress": "In Progress",
    "editableTodoCard.status.blocked": "Blocked",
    "editableTodoCard.status.initial": "Initial",
    "editableTodoCard.status.cancelled": "Cancelled",
    "editableTodoCard.status.inProgress": "In Progress",
    "editableTodoCard.menu.editTask": "Edit Ticket",
    "editableTodoCard.menu.deleteTask": "Decommission Ticket",
    "editableTodoCard.messages.noEnhancedDescription": "No enhanced summary yet. Run diagnostics to generate one.",
    "editableTodoCard.tooltips.enhance": "Diagnostics enhance summary, suggest labels and complexity",
    "editableTodoCard.editMode": "Edit Mode",
    "editableTodoCard.viewMode": "View Mode",
    "editableTodoCard.actions.move": "Reassign",
    "editableTodoCard.actions.clone": "Duplicate",
    "editableTodoCard.actions.flag": "Flag",
    "editableTodoCard.actions.unflag": "Unflag",
    "editableTodoCard.actions.pin": "Pin",
    "editableTodoCard.actions.unpin": "Unpin",
    "editableTodoCard.actions.share": "Share",
    "editableTodoCard.actions.view": "View Details",
    "editableTodoCard.fields.description": "Summary",
    "editableTodoCard.fields.notes": "Comments",
    "editableTodoCard.fields.tags": "Labels",
    "editableTodoCard.fields.priority": "Priority",
    "editableTodoCard.fields.status": "Status",
    "editableTodoCard.fields.project": "Service",
    "editableTodoCard.fields.dueDate": "Due Date",

    # mindMap
    "mindMap.controls.switchToWorldMap": "Open War Room",
    "mindMap.controls.switchToSphere": "Switch to Sphere",
    "mindMap.controls.chaos": "Chaos",
    "mindMap.controls.zoomIn": "Zoom In",
    "mindMap.controls.zoomOut": "Zoom Out",
    "mindMap.controls.reset": "Reset View",
    "mindMap.controls.center": "Center View",
    "mindMap.controls.fit": "Fit to Window",
    "mindMap.controls.fullscreen": "Full Screen",
    "mindMap.controls.exitFullscreen": "Exit Full Screen",
    "mindMap.info.nodeCount": "{{count}} Nodes",
    "mindMap.instructions.dragToMove": "Drag to Move",
    "mindMap.instructions.dragging": "Moving!",
    "mindMap.instructions.touchAndDrag": "Touch & Drag",
    "mindMap.instructions.doubleTapBurst": "Double-tap for burst!",
    "mindMap.instructions.doubleTapPhysics": "Double-tap for physics!",
    "mindMap.filter.title": "Service Filter",
    "mindMap.filter.allProjects": "All Services",
    "mindMap.filter.projectCount": "{{selected}}/{{total}} Services",
    "mindMap.filter.selectAll": "Select All",
    "mindMap.filter.clearAll": "Clear All",
    "mindMap.filter.selectProjects": "Select Services",
    "mindMap.filter.projectsSelected": "{{count}} services selected",
    "mindMap.filter.selectedProjects": "Selected Services ({{count}})",
    "mindMap.tooltips.disableStaticMode": "Disable Static Mode",
    "mindMap.tooltips.enableStaticMode": "Enable Static Mode",
    "mindMap.tooltips.cleanUpEffects": "Clean Up Visual Effects",
    "mindMap.sequence.hideSequence": "Hide Task Sequence",
    "mindMap.sequence.showSequence": "Show AI Task Sequence",
    "mindMap.sequence.analyzeSequences": "Analyze Sequences",
    "mindMap.sequence.stopAnimation": "Stop Animation",
    "mindMap.sequence.animateSequence": "Animate Sequence",
    "mindMap.sequence.shuffleSequence": "Shuffle Sequence Type",
    "mindMap.selection.multipleNodes": "{{count}} nodes selected (Ctrl+Click to add/remove, max 3)",
    "mindMap.nodes.centerBrain": "⚡ OPS CORE",
    "mindMap.nodes.centerWorkshop": "🧠 CONTROL CENTER",
    "mindMap.modes.dynamic": "⚡ Dynamic Mode",
    "mindMap.modes.static": "📖 Static Mode",
    "mindMap.dialog.createNode": "🖥️ Provision Service Node",
    "mindMap.dialog.nodeText": "Node Name",
    "mindMap.nodeInfo.type": "Type",
    "mindMap.nodeInfo.priority": "Priority",
    "mindMap.nodeInfo.energy": "Load",
    "mindMap.filters.all": "All Nodes",
    "mindMap.layout.radial": "Radial Layout",
    "mindMap.layout.force": "Force Layout",
    "mindMap.layout.tree": "Tree Layout",
    "mindMap.layout.grid": "Grid Layout",
    "mindMap.connectNodes": "Link Nodes",
    "mindMap.addNode": "Add Node",

    # chatAssistant
    "chatAssistant.errors.demoUserRestricted": "🚫 AI diagnostics are not available for demo operators. Please provision an account to access AI assistance.",
    "chatAssistant.quickActions.listPending": "List my pending tickets",
    "chatAssistant.quickActions.createHighPriority": "Provision a new critical ticket",
    "chatAssistant.quickActions.summarizeProject": "Summarize the {{project}} service",
    "chatAssistant.quickActions.filterHighPriority": "Show me critical tickets in this service",
    "chatAssistant.suggestedActions.listPending": "List Pending",
    "chatAssistant.suggestedActions.newHighPrio": "New Critical",
    "chatAssistant.suggestedActions.summarize": "Summarize",
    "chatAssistant.status.typing": "Diagnostic system processing",
    "chatAssistant.emptyState.title": "Ops Diagnostic Assistant",
    "chatAssistant.emptyState.demoMessage": "AI diagnostics are not available for demo operators. Provision an account to access AI assistance!",
    "chatAssistant.emptyState.description": "Your diagnostic AI to help manage tickets, services, and more.",
    "chatAssistant.notConfigured.title": "Diagnostic System Offline",
    "chatAssistant.notConfigured.description": "To bring diagnostics online, please configure your AI provider in Settings.",
    "chatAssistant.notConfigured.configureButton": "Configure AI Provider",
    "chatAssistant.header.title": "Ops Diagnostics",
    "chatAssistant.header.refreshTooltip": "Refresh context",
    "chatAssistant.header.settingsTooltip": "Settings",
    "chatAssistant.menu.refreshContext": "Refresh Context",
    "chatAssistant.menu.aiSettings": "AI Settings (Go to Settings)",
    "chatAssistant.menu.aiSettingsRedirect": "AI configuration has been moved to Settings → AI Configuration",
    "chatAssistant.input.placeholder": "Query the diagnostic system...",
    "chatAssistant.input.demoPlaceholder": "AI diagnostics are not available for demo operators. Provision an account!",
    "chatAssistant.send": "Dispatch",
    "chatAssistant.thinking": "Running diagnostics...",
    "chatAssistant.suggestions.searchLessons": "Search runbooks",
    "chatAssistant.suggestions.listTodos": "List active tickets",
    "chatAssistant.suggestions.createProject": "Provision new service",
    "chatAssistant.suggestions.summarize": "Generate status report",
    "chatAssistant.actions.feedback.bad": "Not Useful",
    "chatAssistant.actions.feedback.good": "Useful",
    "chatAssistant.actions.retry": "Retry",
    "chatAssistant.actions.delete": "Purge",

    # mobileChatInterface
    "mobileChatInterface.quickActions.createTodo": "Provision Ticket",
    "mobileChatInterface.quickActions.listTodos": "List Tickets",
    "mobileChatInterface.quickActions.projectStatus": "Service Status",
    "mobileChatInterface.quickActions.help": "Help",
    "mobileChatInterface.quickActions.prioritize": "Triage",
    "mobileChatInterface.quickActions.summarize": "Status Report",
    "mobileChatInterface.actionMessages.createTodo": "Help me provision a new ticket",
    "mobileChatInterface.actionMessages.listTodos": "Show me my current ticket queue",
    "mobileChatInterface.actionMessages.projectStatus": "Give me a status update on my services",
    "mobileChatInterface.actionMessages.help": "What can you help me with?",
    "mobileChatInterface.actionMessages.prioritize": "What should I triage first today?",
    "mobileChatInterface.actionMessages.summarize": "Give me a quick status report on my current service",
    "mobileChatInterface.header.title": "Ops Diagnostics",
    "mobileChatInterface.header.statusListening": "Receiving...",
    "mobileChatInterface.header.statusTyping": "Processing...",
    "mobileChatInterface.header.statusOnline": "Online",
    "mobileChatInterface.emptyState.greeting": "Ops Diagnostic System Online",
    "mobileChatInterface.emptyState.description": "I can help you manage tickets, navigate services, and answer questions about your workspace.",
    "mobileChatInterface.status.thinking": "Running diagnostics...",
    "mobileChatInterface.input.placeholder": "Query the system...",
    "mobileChatInterface.minimize": "Minimize",
    "mobileChatInterface.connectionStatus.disconnected": "Disconnected",
    "mobileChatInterface.connectionStatus.connected": "Connected",
    "mobileChatInterface.connectionStatus.reconnecting": "Reconnecting…",

    # warRoom
    "warRoom.backgroundImage.noUploads": "No custom backgrounds on record",
    "warRoom.backgroundImage.opacity": "Opacity",
    "warRoom.backgroundImage.fitMode": "Fit Mode",
    "warRoom.backgroundImage.fitCover": "Cover",
    "warRoom.backgroundImage.fitContain": "Contain",
    "warRoom.backgroundImage.fitStretch": "Stretch",
    "warRoom.backgroundImage.fitTile": "Tile",
    "warRoom.backgroundImage.blendWithTerrain": "Blend with Terrain",
    "warRoom.backgroundImage.remove": "Remove Background",
    "warRoom.backgroundImage.active": "Active",
    "warRoom.backgroundImage.uploadError": "Upload failed. Please try again.",
    "warRoom.backgroundImage.fileTooLarge": "Image must be under 5MB",
    "warRoom.backgroundImage.invalidType": "Only JPEG, PNG, and WebP images are supported",
    "warRoom.incident.escalate": "Escalate",
    "warRoom.incident.status": "Status",
    "warRoom.empty.action": "Open Incident",
    "warRoom.filters.active": "Active",

    # swarmDesk — keep most technical, voice a few
    "swarmDesk.ui.navigation.controls": "⌨️ Navigation Controls",
    "swarmDesk.ui.navigation.escape": "🚪 ESC: Return to Console | M: Menu",
    "swarmDesk.panels.shortcuts.title": "⌨️ Hotkeys",
    "swarmDesk.panels.shortcuts.categories.navigation.title": "🧭 Navigation",
    "swarmDesk.panels.shortcuts.categories.actions.title": "⚡ Actions",
    "swarmDesk.panels.mcp.tools.connectedAs": "Connected as: {{username}}",
    "swarmDesk.panels.mcp.debug.authentication": "Authentication: {{status}}",
    "swarmDesk.panels.mcp.debug.apiService": "API Service: {{status}}",
    "swarmDesk.panels.agent.interface.role": "Role: {{role}}",
    "swarmDesk.panels.agent.interface.status": "Status: {{status}}",
    "swarmDesk.panels.agent.capabilities.communication": "✅ Real-time Communication",
    "swarmDesk.panels.analytics.insights.peakActivity": "Peak activity: 14:00-15:00",
    "swarmDesk.panels.webllm.compatibility.checkCompatibility": "🔍 Check Compatibility",
    "swarmDesk.panels.webllm.settings.temperature": "Temperature:",
    "swarmDesk.panels.webllm.settings.maxTokens": "Max Tokens:",
    "swarmDesk.panels.mqtt.logs.lastMessage": "Last: {{time}}",
    "swarmDesk.panels.mqtt.status.lastActivity": "Last Activity: {{time}}",
    "swarmDesk.panels.mqtt.settings.showTimestamps": "Show timestamps",
    "swarmDesk.panels.settings": "Config",
    "swarmDesk.panels.chat": "AIs",
    "swarmDesk.panels.insights": "Analytics",
    "swarmDesk.panels.projects": "Services",
    "swarmDesk.panels.todos": "Ticket Queue",
    "swarmDesk.projectData.swarmDesk.status": "🔥 Active Development",
    "swarmDesk.projectData.swarmDesk.visibility": "public repository",
    "swarmDesk.projectData.inventorium.title": "📦 Inventorium",
    "swarmDesk.projectData.swarmonomicon.title": "🐝 Swarmonomicon",
    "swarmDesk.projectData.swarmonomicon.visibility": "public repository",
    "swarmDesk.errors.permissionDenied": "🔒 Access Denied",
    "swarmDesk.errors.unknownError": "❓ Unknown Error",
    "swarmDesk.status.disconnected": "Datastore disconnected",
    "swarmDesk.status.connected": "Connected to datastore",
    "swarmDesk.status.synced": "Synced",
    "swarmDesk.status.syncing": "Syncing…",
    "swarmDesk.controls.zoom": "Zoom",
    "swarmDesk.controls.rotate": "Rotate",
    "swarmDesk.controls.move": "Move",
    "swarmDesk.tour.navigation": "WASD to navigate, mouse to look",
    "swarmDesk.agentPanel.status.active": "Active",
    "swarmDesk.projectPanel.selected": "Active: {{name}}",
    "swarmDesk.hotkeys.mouse": "Mouse: Look",
    "swarmDesk.hotkeys.space": "Space: Select",
    "swarmDesk.hotkeys.wasd": "WASD: Navigate",
    "swarmDesk.nodes.move": "Reassign",
    "swarmDesk.filters.inProgress": "In Progress",
    "swarmDesk.filters.pending": "Pending",
    "swarmDesk.sort.name": "Alphabetical",
    "swarmDesk.sort.priority": "Priority",

    # spells
    "spells.interface.title": "🔧 Ticket Enhancement Tools",
    "spells.interface.subtitle": "Use AI-powered diagnostics to improve your ticket management",
    "spells.interface.selectSpell": "Choose Diagnostic Tool",
    "spells.interface.castSpell": "Run Diagnostic",
    "spells.interface.cancelSpell": "Abort",
    "spells.interface.casting": "Running Diagnostic...",
    "spells.interface.resultsTitle": "✅ Diagnostic Results",
    "spells.interface.historyTitle": "📋 Diagnostic History",
    "spells.interface.clearHistory": "Clear History",
    "spells.interface.noHistory": "No diagnostics have been run",
    "spells.interface.placeholder": "Select a diagnostic to enhance your tickets...",
    "spells.results.geomancy.patterns": "Pattern analysis:",
    "spells.results.latest": "Latest",
    "spells.history.result": "Result:",
    "spells.history.success": "✅ Successful",
    "spells.history.failed": "❌ Failed",
    "spells.history.duration": "Duration:",
    "spells.status.success": "Success",
    "spells.accessDenied.title": "Access Denied",
    "spells.keyboardShortcut": "Hotkey",
    "spells.estimatedTime": "Estimated Time",
    "spells.result.confidence": "Confidence",
    "spells.error.unknown": "An unknown error occurred",
    "spells.enhanceDescription.result.before": "Before",
    "spells.enhanceDescription.result.after": "After",
    "spells.enhanceDescription.result.improvements": "Improvements",
    "spells.performGeomancy.insights.complexity": "Complexity",
    "spells.performGeomancy.insights.duration": "Estimated Duration",
    "spells.performGeomancy.insights.risks": "Risk Factors",
    "spells.categories.consolidate": "Consolidate",
    "spells.categories.analyze": "Analyze",
    "spells.categories.enhance": "Enhance",

    # insights
    "insights.tabs.overview": "Overview",
    "insights.tabs.analytics": "Analytics",
    "insights.tabs.performance": "Performance",

    # admin
    "admin.tabs.overview": "Overview",
    "admin.tabs.analytics": "Analytics",
    "admin.overview.fallback": "(showing mock data for development)",
    "admin.overview.activeUsers": "Active (7d)",
    "admin.overview.errors": "Errors (24h)",
    "admin.analytics.title": "Advanced Analytics",
    "admin.analytics.timeframe.day": "Last 24 Hours",
    "admin.analytics.timeframe.week": "Last 7 Days",
    "admin.analytics.timeframe.month": "Last 30 Days",
    "admin.analytics.timeframe.year": "Last 12 Months",
    "admin.analytics.charts.activityHeatmap": "Activity Heatmap",
    "admin.logs.fallback": "(showing mock data for development)",
    "admin.logs.showing": "Showing",
    "admin.logs.columns.timestamp": "Time",
    "admin.logs.columns.level": "Level",
    "admin.logs.columns.message": "Message",
    "admin.logs.severity.error": "ERROR",
    "admin.logs.severity.warning": "WARNING",
    "admin.logs.severity.info": "INFO",
    "admin.featureFlags.fallback": "(showing mock data for development)",
    "admin.featureFlags.lastUpdated": "Last updated",
    "admin.featureFlags.flags.theme_selector": "Theme Selector",
    "admin.featureFlags.flags.custom_themes": "Custom Themes",
    "admin.featureFlags.flags.api_access": "API Access",
    "admin.featureFlags.flags.analytics": "Analytics",
    "admin.featureFlags.flags.debug_mode": "Debug Mode",
    "admin.users.fallback": "(showing mock data for development)",
    "admin.users.showing": "Showing",
    "admin.users.filtered": "filtered from",
    "admin.users.columns.status": "Status",
    "admin.users.columns.actions": "Actions",
    "admin.common.error": "An error occurred",

    # queuePane
    "queuePane.incoming.title": "Incoming",
    "queuePane.stats.total": "Queued",
    "queuePane.stats.high": "Critical",
    "queuePane.stats.incoming": "Incoming",

    # onboarding
    "onboarding.colors.chipText": "#ffffff",
    "onboarding.steps.add-todo.step1": "Click the floating '+' button again",
    "onboarding.steps.ai-assistant.examplePromptsTitle": "Try querying:",
    "onboarding.steps.swarmdesk.features.interactive": "Interactive navigation",
    "onboarding.steps.swarmdesk.features.architecture": "Architecture overview",
    "onboarding.steps.swarmdesk.features.dependencies": "Dependency mapping",
    "onboarding.steps.complete.nextStepsTitle": "Next Steps:",

    # misc sections
    "lessons.fields.language": "Language/Category",
    "mindmap.controls.zoomIn": "Zoom In",
    "mindmap.controls.zoomOut": "Zoom Out",
    "mindmap.controls.centerView": "Center View",
    "swarmdesk.controls.rotate": "Rotate",
    "swarmdesk.controls.zoom": "Zoom",
    "swarmdesk.controls.pan": "Pan",
    "errors.serverError": "Internal server error.",

    # success
    "success.status.error.title": "VERIFICATION FAILED",
    "success.status.error.subtitle": "The verification process encountered an error.",
    "success.log.session": "Session:",
    "success.log.conduitStable": "Payment confirmed: STABLE",
    "success.log.unlocking": "Unlocking upgraded features...",
    "success.log.paymentIncomplete": "WARNING: Payment incomplete",
    "success.log.error": "ERROR:",
    "success.log.verificationFailed": "Verification failed",
    "success.log.containment": "Error protocols engaged",

    # targetAgent
    "targetAgent.none": "Unassigned",
    "targetAgent.user": "Operator",

    # todoDetail
    "todoDetail.tabs.overview": "Overview",
    "todoDetail.tabs.related": "Related Tickets",
    "todoDetail.tabs.coordinates": "Coordinates",
    "todoDetail.fields.status": "Status",
    "todoDetail.fields.priority": "Priority",
    "todoDetail.fields.project": "Service",

    # automationRecipes
    "automationRecipes.tagNormalization.scanned": "Scanned",
    "automationRecipes.tagNormalization.modified": "Modified",

    # constellation
    "constellation.searchPlaceholder": "Query dependency graph...",
    "constellation.loading": "Mapping dependencies...",
    "constellation.viewModeTooltip": "Dependency Topology",

    # questTab
    "questTab.buttons.add": "Add",
    "questTab.buttons.addChain": "Add Chain",
    "questTab.buttons.removeChain": "Remove chain",
    "questTab.status.active": "Active",
    "questTab.status.completed": "Resolved",
    "questTab.status.pending": "Pending",
    "questTab.filters.all": "All",
    "questTab.filters.active": "Active",
    "questTab.filters.completed": "Resolved",
    "questTab.empty.title": "No active quests",
    "questTab.empty.action": "Create Quest",

    # questCard
    "questCard.external": "external",
    "questCard.briefDismiss": "Dismiss",
    "questCard.copiedPrompt": "Copied!",
    "questCard.copiedId": "Copied!",

    # lessonsViewer
    "lessonsViewer.bench.sectionLessons": "Runbooks",
    "lessonsViewer.neighbors.none": "none",
    "lessonsViewer.references.none": "none",

    # projectSelector
    "projectSelector.placeholder": "Select service...",

    # aiInsights
    "aiInsights.dialog.deselectAll": "None",
}

for path, value in patches.items():
    set_key(labops, path, value)

save("labops", labops)
print("labops.json written")

import subprocess
r = subprocess.run(
    ["node", "-e", "require('./labops.json'); console.log('labops: valid')"],
    capture_output=True, text=True, cwd=THEMES_DIR
)
print(r.stdout.strip() or r.stderr.strip())
